language: c
sudo: false
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
script:
  - arduino --board esp8266:esp8266:generic --save-prefs
  - arduino --verify $PWD/examples/ConvertProntoHex/ConvertProntoHex.ino
